### ISSUE TITLE
takeoff (to) command stopped working

### ISSUE THREAD

**Issue by kaitsu71** [zlsa/atc#691] opened 2016-10-10 18:39 UTC
I played quite a long time today and then suddenly "to" command refused to work. So I gave "caf" command first and then "to" but pressing Enter after to had no effect. All the other commands like "cvs" still worked just fine.

**Comment by eliuuk** [comment] 2016-10-10 19:17
What airport are you playing? This is a known issue in some aerodromes.

**Comment by kaitsu71** [comment] 2016-10-11 14:48
Wait?.. Are there other airports available than KSFO? I just use this URL https://zlsa.github.io/atc/

**Comment by eliuuk** [comment] 2016-10-11 15:25
Yes! The 3rd button to the right is the switch airports button.

**Comment by erikquinn** [comment] 2016-10-11 15:44
@kaitsu71 What is the response that is shown when you type `to` and press enter on a departure?

**Comment by kaitsu71** [comment] 2016-10-11 17:31
There is no any kind of response it just does nothing.

**Comment by eliuuk** [comment] 2016-10-11 18:22
Next time this happens, check the console log and send us the error which is produced. The error log can be seen by pressing F12 on Chrome.

**Comment by erikquinn** [comment] 2016-11-13 00:29
@kaitsu71 Are you able to reproduce this issue? Have you seen it again at all?

@indianbhaji What do you mean "This is a known issue in some aerodromes"? That would be news to me, and if it's true, I'd like to fix it. Unless you just mean how they wont take off without a clearance, which doesn't go through via `caf` if they taxi to a runway that's invalid for their filed SID?

**Comment by eliuuk** [comment] 2016-11-13 00:50
@erikquinn #580, although this issue seems to have been worsened by 3.0

**Comment by erikquinn** [comment] 2016-11-13 00:55
@indianbhaji Gotcha. And if #580 was made worse by 3.0, could you go to that issue when you have a few moments and jot down some brief details on it?

**Comment by n8rzz** [comment] 2016-11-13 01:15
@indianbhaji if you can include any console errors that would also be helpful.

**Comment by scott-j-smith** [comment] 2016-11-14 18:37
I ran into this issue yesterday while playing ESPA for about 30-45 minutes.  In addition, all commands stopped working, not just the "to" command.  I didn't get a console log though, but if I see it again I will try to remember to do that.

**Comment by erikquinn** [comment] 2017-02-05 23:23
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.

**Closed as completed by erikquinn** 2017-02-05 23:23 UTC
Labels: bug, closed during openscope migration
