### ISSUE TITLE
Game load stuck on awe.json

### ISSUE THREAD

**Issue by psycho202** [zlsa/atc#41] opened 2014-12-16 21:01 UTC
Loading http://zlsa.github.io/atc/
Stuck on loading awe.json

Console: 
"[ INFO  ]" "Version v2.1.7" modules.js:124
"[ INFO  ]" "Finished loading 13 modules in 0.079s" modules.js:124
"[ WARN  ]" "Failed to get assets/airlines/awe.json: 0"

**Comment by zlsa** [comment] 2014-12-16 21:27
It's caused by an adblocker... apparently AWE is in a keyword list somewhere. I'll remove AWE for now but I'll need to find a way around this.

**Comment by psycho202** [comment] 2014-12-16 21:28
Confirmed. Turning off Adblock Plus removes the issue.

**Comment by zlsa** [comment] 2014-12-16 21:29
It's also been commented out as no airport uses the US Airways airline yet.

**Comment by zlsa** [comment] 2014-12-16 21:33
EasyList blocks `awe.js` (and presumably `awe.json` as well); I'll contact them and see if I can resolve it.

**Comment by zlsa** [comment] 2014-12-17 22:47
This has been fixed in the latest version of EasyList: http://forums.lanik.us/viewtopic.php?f=64&t=20074

**Closed as completed by zlsa** 2014-12-17 22:47 UTC
Labels: bug

**Comment by Diastro** [comment] 2014-12-17 23:59
Wow that was quick :+1:

**Comment by Diastro** [comment] 2014-12-18 05:10
For anyonw still unable to load the page : 
- Click on the addblock icon (next to the adress bar on Chrome)
- Options
- Click update now which will update EasyList

Should work then
