### ISSUE TITLE
Minor Bugs in v3.2.0

### ISSUE THREAD

**Issue by scott-j-smith** [zlsa/atc#767] opened 2016-12-21 15:31 UTC
Hi Erik,

Started playing on the new version yesterday and noted a few bugs that are the same on at least 3 different airports:

1. Fly Heading (fhxxx) command not working

2. Audio voice read-back of commands sometimes says current altitude instead of target altitude when issuing a climb or descend (e.g. if at FL80 and issue command "d 40" the audio will read back "<call sign> maintain 8000"), but the aircraft will still descend.

3. Arriving aircraft change heading to 360 at the end of their assigned routes now

Let me know if you need further details.
Thanks,
Scott

**Comment by Shirtail** [comment] 2016-12-21 15:39
I've got the same problem Scott. It just started acting up as of yesterday.

**Comment by eliuuk** [comment] 2016-12-21 15:45
The fly heading command has changed, it's no longer fh### but instead
fh ### with the space. There are some efforts at the moment to update the
in-game tutorial.

**Comment by n8rzz** [comment] 2016-12-21 15:46
@scott-j-smith @Shirtail 

Hey guys!

1) was very much intentional.  We completely re-wrote the CommandParser with this release and, as such, that command has changed.  

3) is a known issue in my fork (https://github.com/n8rzz/atc/issues/206) and will be addressed sometime soon.

2) seems legit, we will have to investigate that one a little more.

**Comment by scott-j-smith** [comment] 2016-12-21 15:58
Thanks for the note about he command parsing.  I guess I should read the release notes.  :-)

Regarding #3, I also saw the same behavior for departing aircraft playing on LKPR - maybe I didn't see it on  the other airports I played because they left the airspace before reaching the end of their routes?

And I had an issue on LKPR where I had a departing aircraft waiting to take off, while another one was landing.  When the arriving aircraft switched to ground and was removed from the screen, the game also removed the departing one waiting to take off!  The flight strip was still on the right side, but the white dot and the box were gone -- and I could not issue it any commands (like the command line was frozen -- I didn't even get the "command not understood" read back).   I could still work with other planes though, and the rest of it seemed to still work.    Sorry, but I closed the window by mistake when I mean to resize it to take a screenshot, so I don't have a console view or anything else for you to help explain it.  If I see this again I'll let you know more details.

Thanks,
Scott

**Comment by scott-j-smith** [comment] 2016-12-21 18:33
Well, that last issue I just reported (call it #4) happened again on the same airport.  Screen shot below.

Flight CSA814 was waiting and another plane just landed and switched to ground... now CSA814 disappeared from the map view, and is frozen.

![image](https://cloud.githubusercontent.com/assets/22403776/21400997/95a492b2-c780-11e6-9cab-a1b4c180c272.png)


There are a lot of departure route errors in the console view too, but probably unrelated?

![image](https://cloud.githubusercontent.com/assets/22403776/21401023/ad9bbf6c-c780-11e6-9603-741019f1e4c0.png)

**Comment by Forthwrong** [comment] 2016-12-21 19:40
In addition to encountering 2 and 3, in EGLL I also experienced arrivals that were greyed out even after entering well into my airspace. I believe this has to do with altitude, as I only received descending aircraft. On several occasions, I encountered arrivals that stayed at a particular altitude and always stayed greyed out, out of my control, after passing the last fix in their route (and obviously then heading to 360, as mentioned earlier).

**Comment by erikquinn** [comment] 2016-12-21 23:12
>in EGLL I also experienced arrivals that were greyed out even after entering well into my airspace. I believe this has to do with altitude, as I only received descending aircraft. On several occasions, I encountered arrivals that stayed at a particular altitude and always stayed greyed out, out of my control, after passing the last fix in their route (and obviously then heading to 360, as mentioned earlier).

This sounds to me like an airport design problem... like perhaps they are at an altitude that is outside of the altitude range of the airspace?

**Comment by eliuuk** [comment] 2016-12-21 23:45
@erikquinn Probably, I'll have a look at that. The only problem is that EGLL has a fictional airspace, and descend altitudes are not clearly documented on charts as controllers in the UK descend each aircraft manually, and not through a 'descend via STAR' command.

**Comment by Shirtail** [comment] 2016-12-22 04:08
A/c clrd to a lower altitude on initial contact, a/c responds "maintaining" whatever the assigned enroute altitude is, but then descends to the lower altitude anyway. Happens at all a/ps as far as I know .

**Comment by scott-j-smith** [comment] 2016-12-22 15:37
Issue 4 is not airport specific - same thing happened to me just now playing LOWW.  The game deletes the plane from the waiting queue, it disappears from the map view, and you can issue the takeoff command to the next plane in line (what was number 2 before) and it works...  but it leaves the flight strip for the deleted plane on the right hand side.

**Comment by georgeenciu** [comment] 2016-12-22 16:13
Happened to me before and this one looks like it's going the same way. After the exit point (OSPEN in this case) the plane will turn heading north, re-enter the radar, exit, and award me 10 extra points :) 
![screenshot 2016-12-22 17 59 40](https://cloud.githubusercontent.com/assets/1264087/21431920/fc176d2a-c871-11e6-9c57-c43354438794.png)

**Comment by Fechulo** [comment] 2016-12-23 17:46
Issue 5: assigning an altitude to an aircraft before being cleared as filed doesn't work and throws the following error
![bug 5](https://cloud.githubusercontent.com/assets/13125311/21459611/aaf45022-c937-11e6-8ed2-8188d40a26ad.PNG)

**Comment by panther2** [comment] 2016-12-23 18:14
Yes, issue 5 is addressed here:
https://github.com/n8rzz/atc/issues/228

**Comment by erikquinn** [comment] 2016-12-24 06:22
Notice to airmen:

If additional new issues are encountered, please add individual issues for them rather than adding on to this one; that will make the tracking of the fixes much easier. :)

EQ

**Comment by erikquinn** [comment] 2017-01-16 18:19
1. working properly (command syntax changed)
2. Covered in #769.
3. Covered in n8rzz/atc#206, part of v3.2.1 (which is still pending)
4. Covered in #770.
4a. (inaccessible "greyed out" aircraft) Root cause is covered in #777.
5. Covered in n8rzz/atc#228.

All items are addressed in other issues. Closing.

**Closed as completed by erikquinn** 2017-01-16 18:19 UTC
Labels: bug
