### ISSUE TITLE
Speedbird 330

### ISSUE THREAD

**Issue by bolero3232** [zlsa/atc#405] opened 2016-02-27 01:13 UTC
I'm new to this format. Hope I'm doing it right.
Eventually I always get this message when trying to release an airliner for take off. After this it's impossible to release aircraft. Is it that I've caused a traffic issue of some sort?

**Comment by Fechulo** [comment] 2016-02-27 01:29
I believe this problem has already been addressed in #353.

**Comment by bolero3232** [comment] 2016-02-27 02:50
I don't see how 353 applies. Speedbird 330 does not exist.

**Comment by Fechulo** [comment] 2016-02-27 13:54
Then I'm not sure what your problem is. I understand you're getting some kind of message, could you develop?

**Comment by bolero3232** [comment] 2016-02-29 02:45
The message I get is that the aircraft I'm trying to release is being held up by Speedbird 330, which does not exist. I don't know what else to say.

**Comment by Fechulo** [comment] 2016-02-29 17:30
@bolero3232  Has it happened more than once? If so, was it always BAW330? I recall something similar happening to me a while ago so I started testing and I found that when 2 aircraft collide on the runway the runway becomes unusable, which might be more realistic than just ignoring it. This issue seems to be addressed in #400

**Comment by bolero3232** [comment] 2016-02-29 23:06
Yes it's happened many times. I'll try to catch which aircrafts are involved.
Is there a message log I can check? They scroll away before I can absorb it.

**Comment by Fechulo** [comment] 2016-02-29 23:08
There isn't at the moment unfortunately, though it has been discussed in #341

**Comment by erikquinn** [comment] 2016-03-01 03:18
@bolero3232 Best you could do is to have a look at the runway queue via the console in the debugger (f12 on chrome). If you wander around the return value of...

`airport_get().getRunway("28R")`

...then you should be able to see the queue of that runway (replace "28R" with rwy name of course). The issue is that aircraft like BAW330 can collide with another departure told to taxi quickly after BAW330 is cleared for takeoff, or could also have an arrival crash into them. The point is this:if they are still on the ground, they are in the runway's queue, and won't get removed from it even if they "go boom" and are removed from the game. They are still "1st in line for the runway", which is why the next departure cant use the runway. 

You can do a before and after on the provided command after crashing two on the tarmac and you should be able to reproduce the issue. This should indeed be resolved by #400 as @Fechulo said.

**Comment by erikquinn** [comment] 2016-03-09 16:04
hey @bolero3232, when you get a chance, could you verify that this issue has been fixed? #400 has been merged, and I believe this should solve this issue.

[http://zlsa.github.io/atc](http://zlsa.github.io/atc)

If it is not fixed, just please provide a screenshot or some extra information so the root problem may be identified.

**Comment by erikquinn** [comment] 2016-04-06 17:48
This seems to be fixed. Please advise if you see the issue again.

Closing for now!

**Closed as completed by erikquinn** 2016-04-06 17:48 UTC

**Comment by bolero3232** [comment] 2016-04-09 20:38
Excellent! TY   On 04/06/16, Erik Quinnnotifications@github.com wrote: This seems to be fixed. Please advise if you see the issue again.Closing for now!—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub
