### ISSUE TITLE
Overview of points gained/lost

### ISSUE THREAD

**Issue by stijnsanders** [zlsa/atc#56] opened 2014-12-18 16:46 UTC
I'm not sure why I lose points, or gain them for that matter.
I suggest a list that pops up with the last x things points are added or subtracted for. It would help to know what you were doing wrong.

**Comment by larsen0815** [comment] 2015-01-16 00:15
+1 
Could be shown when clicking on the current points count. Additionally, each time you earn or lose points, this could be noticed in the text area on the lower left.

**Comment by MaicomMR** [comment] 2015-05-25 03:03
+1 Nice idea

**Comment by Maverick283** [comment] 2015-09-09 15:08
A animation could be added for every time the score changes. I'm thinking of that typical "+5 points" animation (Will post a picture if I finally find one) where a text could be added that sums up why the points where gained/lost. Like "Used inactive Runway: -5".

**Comment by sixeyeco** [comment] 2015-12-10 18:54
I'm going to start recording my screen with Camtasia to get a "replay". Maybe that could be an option? In my case I keep hitting terrain and the plane (understandably) immediately disappears from radar. I'm certain that the crashes are my fault (and not a bug) but there's no indication to see where I'm going wrong. Perhaps pulsing or concentric circles? Even a smoke plume would save a lot of binary lives.

**Comment by avdg** [comment] 2015-12-10 19:12
There is some explanation on the wiki, see https://github.com/zlsa/atc/wiki/Scoring.

Of course, there is also the source code, but we shouldn't expect players to read that. Though there is no direct reference to the wiki ingame as well and given its not integrated in the game, it might take players longer before they know the "rules".

**Comment by erikquinn** [comment] 2016-11-20 07:23
This could be implemented via a transparent table that appears on hover over the `$("#score")`, and uses `window.gameController.events` to show how the score total was summed up.

**Comment by erikquinn** [comment] 2017-02-05 23:18
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.

**Closed as completed by erikquinn** 2017-02-05 23:18 UTC
Labels: enhancement, closed during openscope migration
