### ISSUE TITLE
Failures of "caf" and "cvs" need more helpful failure messages

### ISSUE THREAD

**Issue by ghost** [zlsa/atc#771] opened 2016-12-24 05:51 UTC
After issuing "sid JFK3" gives it a new departure, that's not SKORR3, I can then issue "to cvs" as usual.

Javascript console show no errors.

**Comment by scott-j-smith** [comment] 2016-12-24 15:27
This happens on a number of airports actually.   I don't know if this is a bug or expected behaviour though.  Often if you then issue the SID command with the same departure name it will clear as filed then.  Or you can assign a different SID.

**Comment by erikquinn** [comment] 2017-01-02 21:17
Yeah, the "unable to clear as filed" and "unable to climb via sid" messages are annoying and useless. The time needs to be put in to figure out where exactly the giant stack of logic encountered something unexpected, and output a more useful message so the user can get some sort of information about what went wrong. Could be a problem with the airport, could be a problem with a typographical mistake, could be a problem of trying to use a procedure from a runway it doesn't apply to, etc... We should make the errors help the users understand why the command they've entered is impossible to execute properly.

**Comment by erikquinn** [comment] 2017-02-05 23:25
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.

**Closed as completed by erikquinn** 2017-02-05 23:25 UTC
Labels: enhancement, closed during openscope migration
