### ISSUE TITLE
Multiple Background Colors

### ISSUE THREAD

**Issue by MaicomMR** [zlsa/atc#395] opened 2016-02-18 00:38 UTC
Hi everyone, I think about the background color variation, maybe is interesting enable the player to change your background color following your preference. Thought the best location to this option is in options window, to prevent the visual poluition in main screen.
Well, i want to build this, but i didnt have a good java knowledge, i found the background color parameter¹, but i dont know how to build the option to change this field in options screen, someone can help me?

Here is some tests with the possible colors of my idea.

Black = #0e1f2f;
![untitled-111](https://cloud.githubusercontent.com/assets/12571488/13129839/c6226484-d5c6-11e5-81bc-87e264e9d46c.png)

Dark Blue = #171718;
![untitled-112](https://cloud.githubusercontent.com/assets/12571488/13129840/c628533a-d5c6-11e5-80b2-8e39774bb8d0.png)

Default Green = #354;
![untitled-113](https://cloud.githubusercontent.com/assets/12571488/13129841/c62ddd8c-d5c6-11e5-9721-32dea6a482e1.png)

Color path is:
assests/style/ui.js

`html {
  background-color: #354;
  font-family: monoOne, monospace;
}`

**Comment by harp71** [comment] 2016-02-18 06:04
@MaicomMR is already discussed here: #371

**Comment by engeplabs** [comment] 2016-02-19 14:31
@MaicomMR I like that the color of the wind direction indicator is different. Maybe we should implement that too... But I would suggest a less aggressive color than your red. :smile:

**Comment by erikquinn** [comment] 2016-02-19 17:16
@patitoxd The red coloring is actually native, based on the wind being "high" (>8kts) or not. The length of the line also changes based on wind speed. I'm not going a huge fan of the red personally.

**Comment by engeplabs** [comment] 2016-02-19 17:33
@erikquinn haha didn't know that. ^^ should take another peek into the code i guess :wink: but yeah.. I mean this red doesn't match the rest of our colors.

**Comment by erikquinn** [comment] 2016-11-20 07:50
Dupe of #371. Closing.

**Closed as completed by erikquinn** 2016-11-20 07:50 UTC
Labels: duplicate
