### ISSUE TITLE
is ATC broken?

### ISSUE THREAD

**Issue by bolero3232** [zlsa/atc#444] opened 2016-04-13 21:10 UTC
All I get is the green screen with the circles. No runways, no sids, no names... nothing. Mouse has no effect, no zoom, no move.

**Comment by Fechulo** [comment] 2016-04-13 21:13
In which airport are you experiencing this problem?

**Comment by Fechulo** [comment] 2016-04-13 21:25
@erikquinn Seems to be a problem with AUA not loading. Could it be have to do with the changes in #431 ?

**Comment by bolero3232** [comment] 2016-04-13 23:05
All airports.
What's #431?

**Comment by bolero3232** [comment] 2016-04-13 23:05
#431 got it

**Comment by Fechulo** [comment] 2016-04-13 23:19
@bolero3232 It's actually not all airports, the problem is that when one airport fails, all airports after it fail too. The problem seems to be in the airports which include Austrian Airlines, which leads me to believe that this is somehow the cause. Since I'm not the expert here, I am not 100% sure.

**Comment by bolero3232** [comment] 2016-04-14 01:10
So what do I do about it?

**Comment by headphase** [comment] 2016-04-14 01:39
Testing now and at first I thought it might be due to the uncapitalized "b77l" reference in the fleets of those airlines updated by [commit](https://github.com/zlsa/atc/commit/57dec34acc0c077d25fe9a121b573d0255e2602b) but after recapitalization I'm still having issues with random airports.

Working:
KJFK 
KMSP
KSFO
KLAX
KLAX90
EBBR
EDDM
EHAM
ENGM
LTBA
SAEZ
SBGL
SBGR
UUDD
VHHH

Problems occuring / Loading Failing intermittently:
EDDH
EDDT
EIDW
LOWW

Not loading at all (?)
EGLC
EINN

**Comment by erikquinn** [comment] 2016-04-14 01:43
Yeah it's apparently actually due to about a dozen airlines not being called to load. It was like 15 or so, meaning the loading issues would be widespread across the airports, since they all are likely to use one of the affected airlines. Seems impossible that I missed this, as I didn't come across it while testing, but somehow it made it out to the live site. Sorry, this is 100% on me. :disappointed:

I've got them all added in now on a local branch and am just testing the (ahem) _stuff_ out of it before pushing in a hotfix.

**Comment by headphase** [comment] 2016-04-14 01:52
Really? That's odd I was looking through airlines.js on the live site and it seems every company is included on the list 👀

**Comment by erikquinn** [comment] 2016-04-14 01:57
@headphase Just not some of the new ones from #431 apparently. Four are good, the rest are never loaded in `airlines.js`. I was equally surprised not to have noticed it...

@all
**Could some of you verify it is now fixed at this link please?**
[erikquinn.github.io/atc/b/missing-airlines](http://erikquinn.github.io/atc/b/missing-airlines)

**Comment by headphase** [comment] 2016-04-14 02:34
Seems to work for me!

It looks like I also may have accidentally not included an updated airlines.js and aircraft.js in my final commit in #431 ? odd.

**Comment by erikquinn** [comment] 2016-04-14 02:43
@headphase okay, thanks. Looks like we are good to go. I will merge this now, and that should resolve this issue. Thanks for taking the time to verify the fix!

**Closed as completed** 2016-04-14 02:46 UTC
Labels: bug - high priority

**Comment by bolero3232** [comment] 2016-04-14 13:42
Still not working for me.

**Comment by headphase** [comment] 2016-04-14 18:01
@bolero3232 have you refreshed your browser cache?  Typically CTRL+F5

**Comment by bolero3232** [comment] 2016-04-14 22:22
no effect
dammit I liked this game

**Comment by Fechulo** [comment] 2016-04-14 22:23
@bolero3232 Have you tried using incognito mode?

**Comment by bolero3232** [comment] 2016-04-15 00:06
I don't know what that is

**Comment by Fechulo** [comment] 2016-04-15 00:13
If you're using Chrome you can open an incognito Window by pressing shift+ctrl+n

**Comment by bolero3232** [comment] 2016-04-15 00:20
No I just use IE. I think it's InPrivate here. No easy way to disable it.
Anyway, nothing has changed in my system, so I don't think that's the problem.

**Comment by erikquinn** [comment] 2016-04-15 00:25
@bolero3232 Are you definitely using [http://zlsa.github.io/atc](http://zlsa.github.io/atc)? Nobody seems to be having issues, so I'm not sure how to proceed here.

**Comment by erikquinn** [comment] 2016-04-15 11:10
Apparently it's an Internet Explorer specific issue. Created a new issue for this, #450. @bolero3232 In the meantime, you may want to use a different browser (I recommend Google Chrome) until that is fixed.

**Comment by erikquinn** [comment] 2016-04-15 17:18
hey @bolero3232, when you get a chance sometime, could you verify that the issue is fixed at this link?

[erikquinn.github.io/atc/b/ie](http://erikquinn.github.io/atc/b/ie)

This modified version of the sim includes the changes from PR #453 which _should_ resolve your issue with Internet Explorer.

**Comment by bolero3232** [comment] 2016-04-18 02:39
I've just figured out I can run ATC with Microsoft Edge. Before this I was using IE. I have no clue why it won't run on IE anymore.

**Comment by erikquinn** [comment] 2016-04-18 10:25
@bolero3232 Yes, the issue is unique to IE... But it should be resolved at the link I posted above. Please let me know whether or not that link works in IE for you so I can get it merged in. 

[erikquinn.github.io/atc/b/ie](http://erikquinn.github.io/atc/b/ie)

**Comment by bolero3232** [comment] 2016-04-19 21:42
Yes, it does work! Thanks.

**Comment by bolero3232** [comment] 2016-05-12 20:29
erikquinn.github.io/atc/b/ie Error 404
