### ISSUE TITLE
False Positives with "appears on collision course with xxx on same rwy"

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#352] opened 2016-01-21 19:49 UTC
Last Command entered: `DAL672 t r 250 l 28r`

![image](https://cloud.githubusercontent.com/assets/5103735/12492048/4f6f9594-c04c-11e5-9caa-d09ed0a862dc.png)
Whenever I really start to push the envelope as far as getting _really_ close to minimum separation on final, I seem to get a bunch of these guys popping up, telling me that the arrivals all appear to be on a collision course together on the same runway. Seems like a false positive to me? I'm not real familiar with how that separation logic works. All I know is that they are separated, and probably shouldn't be generating any warnings to the user.

Side Note: You'll also notice the >30 degree intercept when using heading 250... which is because the actual heading of 28R is 284. I'll check on it, but I'm pretty sure 250 _is_ used at SFO, which would mean that the 30 degree intercept angle is not based on the runway's actual magnetic heading, but its nominal heading, as in `28R --> 28 --> 280 degrees +/- 30 degree intercept`. I'll look into it, and create a separate issue if needed.

**Comment by tedrek** [comment] 2016-01-22 07:22
Yes the 'appear to be on collision course' warning is a false positive.  I made a fairly major mistake there and haven't gotten around to fixing it.  The problem is the code is checking if the aircraft are assigned to the same hunk of concrete on the ground and they have headings significantly differing.  It should be checking if aircraft are assigned to different ends of the same hunk of concrete (along with distance checks).

**Closed as completed** 2016-02-06 20:23 UTC
