### ISSUE TITLE
System Crash

### ISSUE THREAD

**Issue by soundguy159** [zlsa/atc#459] opened 2016-04-25 05:40 UTC
On multiple occasions now, the ATC Sim will crash. I'm including screen grabs of the error lists the last couple of times this has happened. Anybody have any ideas?
![actsim](https://cloud.githubusercontent.com/assets/18653165/14774669/77fe09d0-0a6d-11e6-9481-965152bb44e6.jpg)
![actsim 2](https://cloud.githubusercontent.com/assets/18653165/14774670/77fe7dde-0a6d-11e6-9646-28632e43a38c.jpg)

**Comment by erikquinn** [comment] 2016-04-25 11:25
@soundguy159 thanks for the screenshots... `util.js:580` is called frequently, as it is used in distance calculations, so this could be just about anything. I am not seeing this error myself... what airport are you using? That could be related. And does it seem to happen with any other airports, or just this one?

And as for the first error, it's been there for a while, and shouldn't be a problem, though we do need to clean it up for the sake of the error log... so the crash is obviously caused by something passing invalid values to the `vsub()` function via `util.js:580`.

**Comment by erikquinn** [comment] 2016-04-25 15:02
Based on the airlines listed, the airport in use has to be EDDH. I've looked into it more, but thus far have been unable to reproduce the error. @soundguy159 Do you remember the last command entered before the crash? That may point us in the right direction.

**Comment by Fechulo** [comment] 2016-04-25 17:14
@erikquinn Found it! When an aircraft is cleared for takeoff from RWY 15 via the RAMAR SID and it's clicked after departure, the game crashes. The bug is in line 128 of the EDDH.js file, It should be fixed by #460

**Closed as completed** 2016-04-25 18:09 UTC
Labels: bug - high priority
