### ISSUE TITLE
New json-structure for aircrafts based on performance database

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#298] opened 2015-12-22 16:13 UTC
I started a new issue from zlsa/atc/issues/220 (Some thoughts on enhancements)

As to the reorganisation of the aircrafts performance data i did research as good as i could, and i found some interessting data. Regarding the rate of realism however i had to conlude, that one cannot simulate reality a 100%, as there are so many variables in play. An A320 for example can fly short to mid-range (fuel), with 20 or 150 passengers and their luggage. This would result in a totaly different performance for the same aircraft.
On the other hand the simulation starts just above 10000 feet and for ATC-purposes it doesn´t realy mater, if there is a ton or 10 more weight on an aircraft.

I´d like to make a proposal as to the new json-structure of aircrafts, based on the relevant data for this simulation and the database (eurocontrol, see below 1.) on aircraft performances i found, as follows. I suggest to rewrite all existing aircraft (i offered to do that) and leave some kind of reference (_comment) in each file for new aircrafts, where to get the data from. 

Here my example for an A320, reference here: https://contentzone.eurocontrol.int/aircraftperformance/details.aspx?ICAO=A320&

``` javascript
{
 "_comment": "get aircraft data from: https://contentzone.eurocontrol.int/aircraftperformance/",
 "manufacturer": "Airbus",
 "name": "Airbus A320",
 "type": {
     "icao": "A320", 
     "typecode": "L2J", // = Landplane, 2-Engines, Jet-Engine (see below 2.)
 },
 "takeoff": {
     "iasv2": 145, // minimum takeoff speed
     "runway": 2190, // minimum runway length
     "wtc": "M" // Wake Turbulence Category (L/M/H/SH, see below 4.)
 },
 "climb": {
     "ias50": 175, // Indicated Air Speed takeoff to 5000 feet
     "ias150": 290, // Indicated Air Speed 5000 feet to 15000 feet
     "roc50": 2500, // Rate Of Climb takeoff to 5000 feet
     "roc150": 2000 // Rate Of Climb 5000 feet to 15000 feet
 },
 "approach": {
     "ias100": 290, // Indicated Air Speed above 10000 feet
     "iasapp": 250, // Indicated Air Speed below 10000 feet
     "mcs": 210, // Minimum control speeds below 10000 feet (see below 5.)
     "rod100": 3500, // Rate Of Descent above 10000 feet
     "rodapp": 1000 // Rate Of Descent below 10000 feet
 },
 "landing": {
     "iasmin": 137, // Minimum speed of the aircraft
     "apc": "C", // Approach Speed Categorisation (A-E, see below 3.)
     "runway": 1440 // minimum runway length
 }
}
```

**It would also be great to add an option to show data from this within the aircraft on the canvas-label , e.g. "aircraft-type" next to flightnumber, altitude and speed. Altitude should also show assigned altitude next to real altitude directly in the canvas-label (100|93).**

For those of you who want to dive more into the matter here are some references i found while researching:
1. Aircraft Database Eurocontrol: https://contentzone.eurocontrol.int/aircraftperformance/
2. Aircraft Database Bank of Aircraft HowTo: http://www.bankofaircraft.com/aircraft/how-to-use-this-website/
3. Definition APC (Approach Speed Categorisation): http://www.skybrary.aero/index.php/Approach_Speed_Categorisation
4. Definition WTC (Wake Turbulence Category): http://www.skybrary.aero/index.php/ICAO_Wake_Turbulence_Category
5. Definition MCS (Minimum control speeds): https://en.wikipedia.org/wiki/Minimum_control_speeds
6. Funtamentals of Air Traffic Control: https://books.google.de/books?id=6yhTiGC3ulcC

**Comment by erikquinn** [comment] 2015-12-22 17:31
This would be just glorious. I was thinking about it a while ago, and the detail included above would make a huge difference to make the planes move a little more... right. lol

Although, I hesitate a bit on the actual values... approach.mcs, approach.rod100, approach.rodapp don't really seem to make a lot of sense. You can assign as low as 170 knots to a jet within 20 flying miles of the destination airport (USA at least) and they can comply easily (they have to throw out a bunch of surfaces sure, where 210 is nicer because they can fly 'clean'), so there's no reason for a strict "minimum" of 210. And rate of descent I've always thought was slow, but -1000fpm is even slower than the sim, I think those would be better around -2500 to -3000 for both...

Nonetheless, this would be an excellent improvement.

**Comment by erikquinn** [comment] 2015-12-22 17:34
Correction: Apparently approach.mcs is just Vmc (speed to stay afloat once you've toasted an engine without the plane gettin' all squirrely). So I can't argue with those figures, but now knowing the proper meaning, it wouldn't be applied as a "minimum speed you can assign below 10k ft", which would mean the minimum you could give would theoretically be landing.iasmin, a figure which is much more appropriate. Sorry, should have read it all the way!

**Comment by Maverick283** [comment] 2015-12-22 17:41
I agree, the current performance data is quite simple and reworking the format would be a great addition! 
As mentioned by @erikquinn a Airbus can go much lower then 210 without  issues, and landing speed is as you said way lower with flaps deployed... Instead I'd suggest a StallSpeedClean and a StallSpeedFullFlaps. A aircraft may not fly slower then the clean stall speed when either   20nm away from the airport or not on the localiser. 
I like the idea of the altitude assigned and actual altitude label, as this helps remember what an aircraft was assigned.

**Comment by culebron** [comment] 2015-12-22 22:10
I did play with Vr & V2, and it looked more realistic.

As for acceleration and breaking, my concern is if we have enough data to generate the climb rates for all types.

![selection_056](https://cloud.githubusercontent.com/assets/119675/11967233/f4c69920-a922-11e5-9eda-e0f37107bfaa.png)

I thought what if we just put the widely available figures, like engines thrust and mass (like maximum landing weight), set max speed to 400 KIAS and just figure out everything from an equasion? If we have thrust = drag at 400 KIAS, and assume thrust is equal, then we can get accelerations and climb rates.

Then we'll not need to write down runway length or other derived performance data.

**Comment by harp71** [comment] 2015-12-22 23:01
@erikquinn The eurocontrol database is the only one i found with a lot of aircrafts and data in the same structure for all aircraft. Certainly these values are just constants to be used in equation of your likeings. I think it is important to have the same, comparable base-values for each aircraft from the same source, even if the data seems off a little. Eurocontrol is, however, a quit reliable source i think.

@culebron Calculating the performance from weight and thrust sound awesome. Is that all you need? It is wildly outside my possibilities of programming and/or science to even take a guess if that is realistic :)

**Comment by culebron** [comment] 2015-12-22 23:32
@harp71 I did a quick check, and here's what I see: if we assume best AoA and highest climb rate, then yes, it is possible to calculate the climb rate from speed, mass and thrust. The problem is to estimate nominal thrust, which is significantly lower than take off thrust (and we need TO thrust too, for take off dynamics). Public sources usually quote only TO thrust, so the problem is how to estimate nominal thrust. Need to think.

For landing configurations, at slow speeds planes lower flaps and have high drag, low speed and high thrust, so we also need a guestimate for flaps.

Overall, probably, the task is similar in complexity.

**Comment by Maverick283** [comment] 2015-12-23 00:14
@culebron Well this approach sounds a whole lot better!! :smile: 

From AirbusX and Boeing NGX I would say climb thrust is about 85% - 90% of TO Thrust [(see here for a detailed description of a start phase in a simulated 737)](http://aviation.stackexchange.com/questions/7815/why-do-the-engines-seem-to-power-down-and-then-back-up-after-take-off/7819#7819) . I have two suggestions to figure it out though:
A buddy of mine flies a 737, another one a Dash Q8, i could ask them for those numbers ;)
Alternatively, we could reverse calculate (which i think is more accurate as we stay internal) when we know the best rate of climb speed with the appropriate rate of climb and get the amount of thrust needed for that speed to be reached with this rate of climb.

**Comment by tedrek** [comment] 2015-12-23 08:35
@culebron, we'd also need at least two typical masses for the aircraft one for departure and one for arrivals.

If I'm following you right about calculating acceleration/climb from thrust, then we also need a drag value.  Your proposal is to calculate drag by assuming a 400 KIAS maximum speed due to drag. From what I can find many jet aircraft have engines on them which are capable of thrust levels which would push the airframe to mach 1 or higher; the limiting factor is generally airframe strength rather than available power.  Instead we could calculate a drag factor from published cruise speeds and typical cruise power settings, from googling I'd suggest 80% of power as a default to start with.

**Comment by harp71** [comment] 2015-12-23 15:04
@culebron my aim for accuracy maybe was a little misguided. And as i said, i don´t have a clue how you gonna calculate all that stuff. Therefor another, more simplistic suggestion: by your screenshot i understand you took a look at the bankofaircraft.com database. Their data is more categorized, which i find useful for this purpose. Your aim, i think, is to reduce the constants and do more math. 
Based on the bankofaircraft.com database a aicrafts json could look like that:

``` javascript
{
    "_comment": "get aircraft data from: http://www.bankofaircraft.com/aircraft/",
    "name": "Airbus A320",
    "icao-type-designator": "A320",
    "icao-type-description": "l2j",
    "wake-turbulance-category": "medium",
    "typical-cruising-speed": "medium",
    "climb-performance": "good",
    "approach-category": "c",
    "capacity": 150,
    "mtow": 78000
}
```

What do we know from this data:
- It is a two-engine Jet-aircraft
- with medium wake, which means horizontal separation can vary from 4-6 NM, depending on the wtc of the aircraft in front
- a cruising speed from mach .75 to mach .79
- a climb-rate of aprox. 2500 ft/min
- an approach speed between 121 and 140 knots
  All this data can and should vary based on the MTOW, wich i think is realistically between 85% and 99% in commercial aviation, as the airlines like to fly fully loaded.
  A good randomization from aircraft to aircraft within ranges would then provide a proper realism, just from this few constants, i think.

**Comment by erikquinn** [comment] 2017-02-05 23:18
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.

**Closed as completed by erikquinn** 2017-02-05 23:18 UTC
Labels: enhancement, closed during openscope migration
