### ISSUE TITLE
Aircraft leave airspace while following STAR

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#511] opened 2016-05-17 20:48 UTC
Last time I found a bug, I made a video recreating it, and I realized it was a bit easier than writing it here. I found another issue, so I made a [video](https://www.youtube.com/watch?v=MNQjw9_cL0g) about it! That said, I did have to record it 29 times, until I was happy with the results, so maybe it's not easier. :smile:

**Comment by erikquinn** [comment] 2016-05-20 18:56
This is pretty strange. I have a theory though:

I believe the issue is probably that the London TMA is like a TCA/PCA in the US/Canada, where an elevated classification of airspace prevents aircraft from entering it without being forced to talk to ATC and obtain a specific clearance authorizing them to enter. This is the case in Class B TCA (an inherent PCA) in the US. UK uses the same airspace classification letter range to mean different things, so don't ask me what the UK version of a Class B is lol (whatever the highest you can have around an airport).

In my experience, the TCA/PCA is _NEVER_ all the airspace a given facility owns. For example, the Seattle Class B airspace is small, but the Seattle TRACON approach control facility also owns an "associated outer area", which is typically Class E airspace. The TCA is always super easy to find (looking at you, skyvector!), but the boundaries of the class E are just about impossible. They don't seem to be published anywhere, and the only way I've been able to infer them is from diagrams and video maps.

Seattle Airspace: (blue is Class B PCA, pink lines are all a/s owned by S43 TRACON)
![image](https://cloud.githubusercontent.com/assets/5103735/15438473/fce41c06-1e91-11e6-9c4a-1092df274bd9.png)

So my theory is that you need to find the boundaries of the associated outer area, which (given that the UK shares this stuff like never), might be impossible. VATSIM is probably the only prayer; if they don't have it, I suspect nobody does.

**Comment by Fechulo** [comment] 2016-05-20 19:50
I'm probably not going to find the area we're looking for. Regarding VATSIM, they actually divide the airspace differently than they would IRL. They do this to distribute the traffic better. They have 4 areas: LON_S_CTR, LON_C_CTR, LON_N_CTR and LON_W_CTR. This is how the division works:
![image](https://cloud.githubusercontent.com/assets/13125311/15440158/d650bac4-1ecb-11e6-8d68-8ad9c36f5e32.png)
To our advantage, they often merge LON_S_CTR and LON_C_CTR into LON_SC_CTR which would work perfectly in our case. The problem is that I haven't been able to find the coordinates of this area. I've checked many sector files for the UK but I didn't find anything useful.

**Comment by erikquinn** [comment] 2016-05-20 20:08
That would be a reasonable solution, I think. I'm sure they must have those lines depicted in their sector files somewhere though...

**Comment by Fechulo** [comment] 2016-05-20 20:23
I'll definitely take another look. For the moment, it seems like the area is somewhat defined by restricted areas and airways, so if we don't find anything, we could use that.

**Comment by Fechulo** [comment] 2016-05-20 21:52
I couldn't find anything in the sector files, so I tried to plot LON_SC_CTR on SkyVector, and I think it works! It's not perfect, but nobody's going to notice:
![lon_sc_ctr](https://cloud.githubusercontent.com/assets/13125311/15442692/a3015b92-1eda-11e6-87a9-50769adb444e.PNG)
Here's how it looks like in the sim:
![sim](https://cloud.githubusercontent.com/assets/13125311/15442867/d67be7fc-1edb-11e6-970c-095262eabb87.PNG)
My only problem with using LON_SC_CTR is that it's way too big. Another option could be incorporating some other TMA's (pink) around the London TMA we already have (red):
![cheecky](https://cloud.githubusercontent.com/assets/13125311/15443089/79d02cbe-1edd-11e6-900b-7b8c37027076.PNG)
This solution isn't as realistic, but it looks better and the size is definitely better.

**Comment by erikquinn** [comment] 2016-06-03 20:16
I believe this is resolved as of the merge of #533. Closing.

**Closed as completed by erikquinn** 2016-06-03 20:16 UTC
