### ISSUE TITLE
Taxi/Wait puts flights on the runway causing incursions/collisions. 

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#350] opened 2016-01-20 20:16 UTC
At SFO there was a collision between a flight was cleared to take off and one that was waiting at the same runway. 

The only command I issued to the latter flight was 

> C 100 SP 450 W 28R 

https://www.youtube.com/watch?v=6xovvGCUnVw

I'm certain it would help if I mention that I was playing a forked version that's located here: http://sixeyeco.github.io/atc/ but the only edit I've made was to delete the first way point for SID Offshore.

**Comment by tedrek** [comment] 2016-01-22 08:10
It looks like the delay for aircraft told to wait at a runway may be short enough that the preceding aircraft hasn't had time to move far enough down the runway to prevent a collision.

In game terms a collision is any aircraft which are within 160 feet vertically and laterally of each other.  At KSFO there is a 2-5 second delay for aircraft to appear on the runway, it looks like this time the delay was on the short end and the command was given shortly after the takeoff command.

Increasing the delay after an aircraft is given takeoff clearance would probably solve the issue, or doing a distance check before entering the runway.

**Comment by erikquinn** [comment] 2016-01-22 13:39
@tedrek Does that mean that giving a taxi command puts the aircraft ON the runway???

**Comment by tedrek** [comment] 2016-01-25 06:47
@erikquinn, giving a taxi command doesn't directly put an aircraft on the runway.  It puts the aircraft on the runway after a delay (2 to 5 seconds by default).  An aircraft already being on the runway waiting for the takeoff command causes different behavior, as does an aircraft which has been told to taxi to the runway but hasn't yet been placed on the runway.

**Comment by harp71** [comment] 2016-01-25 09:43
So i use w for wait because ist shorter than taxi. That´s not the same then? i´m all for short abbreviations!

**Comment by tedrek** [comment] 2016-01-25 17:03
@harp71, `w` gives identical in game behavior as `taxi`.

**Comment by erikquinn** [comment] 2016-01-25 18:26
> @erikquinn, giving a taxi command [...] puts the aircraft on the runway

This is what I've always figured, which explains why "wait" is a synonym for taxi. I have always been somewhat confused by the use of "w 28r", as it is entirely a different thing from "t 28r" when said verbally.
- "t 28r" would roughly equate to "Runway 28R, taxi via Alpha, Echo, Charlie, hold short of Runway 28L."
  - this gets them taxiing along a route to the specified runway, where they **hold short of it**
- "w 28r" would equate to "Runway 28R, line up and _wait_."
  - once holding short, this tells them to taxi into position on the runway and wait for t/o clearance

Thus, the use of "w 28r" made me think whenever i told them to "taxi"/"wait", they were actually doing line-up-and-wait. I eventually found this wasn't the case, because arrivals could land on 28R without penalty after telling an a/c to LUAW, when that would result in the arrival landing on top of the guy sitting on the runway...

So it's almost like the taxi/wait command _does_ move them on to the runway, as @tedrek said, but at the same time, their presence "on the runway" doesn't seem to be an issue with the arrivals, when there would realistically be a fireball on the airfield. Yet, if you give the aircraft waiting on the runway a takeoff clearance a second before the arrival lands, then you have an issue... I'm not sure if this is making any sense, but the point is I've never quite understood how they work, and that's part of the trouble with trying to figure out the root cause of the original issue brought up by @sixeyeco above.

**Comment by sixeyeco** [comment] 2016-01-25 20:08
@erikquinn I totally concur. I have had an arriving flight land directly over a departing craft that was "lit up" on a runway without triggering a penalty or worse. I have actually cleared a flight moments before a flight landed without penalty or worse. Now, we're facing an situation in which a craft that has already taken off collides with a flight that is given permission to "wait". 

I can't help but wonder if there's a quick solution to this concern in the "invincibility" feature. I have no clue what initiates invincibility but what if it were extended to include flights that have been told to "taxi" or to "wait"? The clock wouldn't start until it's cleared to takeoff so as to not impact its effectiveness. Arriving flights would have to override that invincibility so that a craft on the runway would trigger a penalty. 

<i>Cons to this quick fix: We still haven't determined the root cause of the issue and this quick fix would depend on another quick fix (allowing legal parallel departures).</i>

As far as terminology is concerned, back in 2010 or so it appears that the U.S. finally capitulated and adopted "line up and wait". This move facilitated standardization within the international aviation community and reduced runway incursions. Perhaps we could do the same thing?
- <b>"Taxi"</b> move from jetway <i><b>to</b></i> the runway. Flights <b><i>do not</b></i> "light up" on radar.
- <b>"Wait" </b>move from jetway <i><b>to</b></i> the centerline on the runway. Flights <b><i>do</i></b> "light up" on radar. 
- <b>"Takeoff"</b> clears the flight to takeoff (subsequent to a "taxi" or "wait" command).

If so, then..the 2-5 second delay should be eliminated for flights that are already on the runway. In other words, if I have 4 flights on the runway then they should each "light up" on radar the moment they become first in line. Flights that are directed to "wait" after having been directed to "taxi" should still be delayed to mimic the time it takes to line up. Do we need to consider the status displayed on the strip? Ready, waiting, taxi, etc?

Regarding shortcuts, I would rather see "t" be an alias for taxi because:  
- "Takeoff" is used so much more often than "Turn".
- "Turn" already has another alias (h).
- "Wait" and "Taxi" are no longer interchangeable (assuming we make these changes).

**Comment by erikquinn** [comment] 2016-01-26 04:25
If I'm being honest, I'd just throw `wait` straight into the can... there's no real reason we can't get by with just `taxi` and `takeoff`. Only funny business is that I don't know what the abbreviated command would be, as `t` is used by turn and unavailable to `taxi`. Seems wiser to me to just do that, because there's no real reason we would use LUAW... it's not like it provides a significant advantage the way this game is played (in real life, though, it makes a _world_ of difference lol)

**Comment by harp71** [comment] 2016-01-26 06:16
I don´t think you need wait as separate command either. Just set wait and
taxi the same, meaning "go there but don´t line-up" and us "w" or "ta"
as abbreviation.
One thing though: you have to see a waiting aircraft standing there. At the
moment if you taxi there, there is no visual indication of an aircraft
waiting at the runway!

And if you make/leave wait an extra command, then the result of an aircraft
lining up and another plane landing on the same runway would in 99% not be
a collision but a go-around for the landing aircraft, as pilots would not
try to land with an aircraft lined up, unless its to late and they can´t
react fast enough.

2016-01-26 5:25 GMT+01:00 Erik Quinn notifications@github.com:

**Comment by sixeyeco** [comment] 2016-01-26 06:58
> At the moment if you taxi there, there is no visual indication of an aircraft
> waiting at the runway!

How about shadow tags? The style sheet could specify z-index, opacity and offsets to create a stack effect. I wouldn't make them clickable though. If there are waiting flights on 28L then they should stack toward 4:30 (SSE). This would also make it easier to see <i>how many </i>craft you have waiting at a given runway. 

![image](https://cloud.githubusercontent.com/assets/179496/12574107/ade98208-c3b5-11e5-90fa-63fbdd8c766f.png)

**Comment by Maverick283** [comment] 2016-04-29 10:30
This is still an issue... It'd be awsome if it could be fixed ASAP, as it really slows you down when you can have no airplanes in cue for takeoff.

**Comment by erikquinn** [comment] 2016-04-29 10:36
@maverick283 yeah, I actually threw in a temporary fix for this into the work I'm doing on #461, which is almost ready, and will be opened up to everybody for testing today. Once that gets merged, all aircraft on the ground are invincible, and the weird long delay between aircraft in line for departure is also removed. A real fix can be implemented later when a tower mode or runway separation rules are implemented. So I think this will be less of an issue in about a week.

**Closed as completed** 2016-05-10 05:26 UTC
Labels: undesirable behavior
