### ISSUE TITLE
Issuing a "heading" command after "fix" (vice versa)?

### ISSUE THREAD

**Issue by siyuanr** [zlsa/atc#379] opened 2016-02-07 03:58 UTC
Currently `heading` and `fix` commands would override each other. Is it possible to implement a consecutive command structure here via a `then` clause? For example, `f ATENA then h 360` would order the plane to turn 360 after reaching `ATENA`.

Or we could use a `cross` clause to note the specific point of executing the next command. For example: `h 360 cross ATENA h 340` tells the plane to head 360 for now; head 340 after `ATENA`. We could then have:
- `cross ATENA`: the "if" clause is the plane reaching a fix;
- `cross ATENA XXX`: the "if" clause is the angle of line between plane and fix reaching XXX (crossing a radial);
- `cross ATENA XX` or `cross ATENA X`: the "if" clause is the distance in NM between plane and fix reaching XX or X (crossing a DME measurement).

The top use case for consecutive commands is SID. It may also come in handy for ILS approaches.

**Comment by sixeyeco** [comment] 2016-02-07 15:17
@siyuanr :+1: 

> It may also come in handy for ILS approaches. 

I'm really challenging myself with [the "reopened airport scenario" on my fork](sixeyeco.github.io/atc/). Typically, I issue `f faith wetor`. Then, I have to issue another command to land. The ability to issue `f faith wetor then L28L` would be incredibly beneficial.

**Comment by tedrek** [comment] 2016-02-07 21:21
This topic is currently being discussed at #315

**Comment by erikquinn** [comment] 2016-06-03 20:44
Duplicate of #315. Closing.

**Closed as completed by erikquinn** 2016-06-03 20:44 UTC
Labels: duplicate
