### ISSUE TITLE
Differentiating Holding short and lining up

### ISSUE THREAD

**Issue by kevini15** [zlsa/atc#406] opened 2016-02-27 10:51 UTC
Hello,
at this moment, there is only one way of "preparing" an aircraft for takeoff (taxi/wait). Even though the aircraft says it is **holding short** of a runway it actually is already **lined up** . I'm saying this, because landing aircrafts normally wouldn't collide with an airplane **held short**, but only with **lined up** ones. I'm pretty new to this game, maybe I just haven't found out about a specific **hold short** command?

My definitions of holding short and lining up:
![runway36](https://cloud.githubusercontent.com/assets/17512423/13372564/6e04b5fc-dd48-11e5-8859-8f41970559e4.gif)

**Comment by harp71** [comment] 2016-02-27 12:54
@kevini15 your absolutely right, There seems to be some confusion and discussion about that somewhere else here, also regarding a bug, where a collision leads to an error not being able to have another takeoff from that runway. I agree, there are two commands necessary: "hold short" off runway and "line up" on runway. Also, in my opinion, a collision should only happen if you line-up or give takeoff clearance to a departing aircraft right before an arriving airplane is about to touchdown (within 4-5 seconds). Otherwise, in reality, it would just lead to a go-around ... after all, pilots are not blind :)

**Comment by Maverick283** [comment] 2016-02-28 21:23
I am of the belive that "taxi" makes them hold short... I'm SFO, you can easily check that by looking at the heading of the aircraft that is "holding short", it is perpendicular to the runway. I believe... Can't test it right now. 

But I agree, taxi should not be a single command, I think it needs to be followed by either "line up and wait" or hold short. So "Speedbird 123, taxi to runway 23 and hold short"  (written as "BA123 taxi 23 hs" )  or "Speedbird 123, taxi to runway 23, line up and wait"  (written as "BA123 taxi 23 luw") is something that could do. 

I agree that an aircraft should do a go around if it is not too close to the runway... Actually I guess I with good visibility even if a taxing aircraft commences to take the runway,  an approaching one would go around. Yet if it does go around, the departing one should not cancel the takeoff unless the aircraft performing the go around is way ahead. @harp71 is right, pilots are not blind, but they can't look behind and up... And the TCAS is put on TA (so it only transmits, I believe to reduce panic attacks when a taxing aircraft forgot to turn it's TCAS off), it won't warn them.

**Comment by kevini15** [comment] 2016-02-29 16:23
All I'm trying to point out is that, even though the aircraft says it's holding short, it's actually lined up on the runway. I'm saying that, because landing planes still crash into planes that are (supposed to be) "holding short".

Maybe someone could implement these changes like following:

lw             for line up and wait
hs / taxi    hold short of runway
to             take off
abort       abort take-off

Another question:  I've read somewhere that you can change an airplanes runway, even after you have assigned it a runway. I've tried it several times with "XXX abort taxi YY" while YY being another runway.

**Comment by Fechulo** [comment] 2016-02-29 17:22
@kevini15 you can change the runway as long as the aircraft isn't in the runway already. You can only do this while the aircraft is taxiing.

**Comment by kevini15** [comment] 2016-02-29 20:39
@Fechulo Oh, ok that makes sense,... they usually don't take much time to taxi to the runway so that explains a lot

**Comment by Fechulo** [comment] 2016-02-29 23:03
@kevini15 In the airport file, the time an aircraft takes to taxi to the runways can be specified, however not many airports use this feature. I personally think it would make sense to maybe add a delay to all airports to make it easier to abort taxi. Let me know what you think.

**Comment by erikquinn** [comment] 2016-03-01 03:06
To be honest, why not just fix the actual problem here: the issue is that aircraft told to "taxi" can collide with arrivals, which is outlandishly absurd, because they will hold short of the runway until told to line-up-and-wait or take off... I would vote to simply make "taxi" cause them to hold short by default, since that's how it works. Then the core problem would be resolved.

And if we wanted to add LUAW later on (not that we are pushing enough volume to necessitate it in most cases), then that could be implemented separately, and probably fairly easy. Personally though, I can live without it as this is primarily a radar simulator. Only if and when we get a "tower mode" would it be even worth having the command. My two cents anyway.

**Comment by Fechulo** [comment] 2016-03-01 18:00
@erikquinn I agree, taxi vs. hold short issue is being discussed somewhere else, so i'd sugges6t closing this one.

**Comment by kevini15** [comment] 2016-03-02 16:49
Alright, thank you for all your comments and posts,.. since I'm new to github, what is going to happen now?

**Comment by Fechulo** [comment] 2016-03-02 16:54
Someone who knows javascript is going to start working on it (this doesn't mean it will be fixed tomorrow, it could take a while).

**Comment by kevini15** [comment] 2016-03-02 17:25
ok, nice to know! so excited for the change!!

**Comment by nielsvdweide** [comment] 2016-05-23 15:34
Any updates on this?

**Comment by nielsvdweide** [comment] 2016-05-23 15:34
Any updates on this? @Fechulo @MaicomMR @erikquinn @Maverick283

**Comment by erikquinn** [comment] 2016-05-23 16:18
@nielsvdweide Sort of... departures that are ready at the end of the runway will not cause conflicts or sep losses with arrivals anymore. So it's somewhat like they're "holding short", but they still technically aren't. And the crazy long taxi delay when you send a slew of departures to the runway at the same time is gone. As soon as one is cleared for takeoff, if the next has had enough time to get to the runway since being given the taxi command, their data block will immediately be visible (and overlapping the departure that just began their takeoff roll)

**Comment by Maverick283** [comment] 2016-06-13 17:43
To get this topic stared again and with #558 in the back of my mind, I think that aircrafts are generally way too fast at the runway for them to be considered taxiing. I think maybe the term "taxi" is wrong here.

Generally a aircraft is directed to the runway by ground control. When holding short (or shortly before, also depending on the airport) it is handed over to tower. This is a difficult question as it questions the prinziple of the simulator as it is right now but: Wheat kind of sim is it? Ground - Tower - Departure - Arrival Simulator? If yes, then ground is difinitely not implemented enough. If it is only a tower-dep-arr sim then ground is implemented to much in my honest opinion.

Maybe, rather then having the aircraft ready to taxi, they should report ready for departure, holding short of a runway. and rather then navigating the aircraft to the runway ("DH1234 taxi 28R") you could tell ground to make aircraft taxi to a runway ("to runway 28R") or even to split it up ("to runway 28R20/28L80" where 20% would go to 28R and 80% to 28R). This might go to far, but it is just some ideas to clear up a little. Maybe someone has some more inputs on this. 
I think

**Comment by Alpi-no** [comment] 2016-06-13 17:48
@Maverick283 I totally agree with your point. I also think the `cvs` and `taxi` should be done either by the computer or a different sim. GND Sim would be very cool though :D but before we tackle this, we should allow to change the wind in an easy way

**Comment by nielsvdweide** [comment] 2016-06-13 18:02
@Maverick283 I love your idea of how airplanes should report ready for departure at the holding short position. In the normal world as you all know there are many controllers at the airport (Delivery/Ground/Tower/Radar). We have discussed the role of the simulator already a couple of times but I believe we just have to do to much as the simulator is becoming more dense and more difficult to play.

I would like to see them reporting ready for departure with the SID already pre-assigned (by the computer) and you only have to give them a take-off clearance.

**Comment by erikquinn** [comment] 2016-06-13 18:50
Personally, I might even like to see it go further and remove _ALL_ tower functions. If we are an approach/departure radar controller, let it be such! Departures take off automatically. All we do is get them to their departure fix, and sequence the arrivals onto final. If it's good enough for real life, it's good enough for us I think! lol

And then separately (later), there would be a "tower" mode where we would have them lined up on approach, and clear arrivals to land, give IFR clearances, taxi instructions, clear departures for takeoff, etc.

**Comment by nielsvdweide** [comment] 2016-06-13 19:00
We could go and remove all tower functions to be fair. If we would implement that we have to be very careful about rate of departures and possibly even a way to (temporarily) stop aircraft to depart if the airspace is becoming too crowded... (which adds congestion on the ground and maybe even points to be deducted)

But if we remove the tower function, I guess the gameplay would be less exciting. With the new SIDS and STARS + Transitions implemented they will automatically fly the path to the runway and there would be little radar vectoring. The only thing we would have to do is give altitude and speed clearances.

So if we want to do this, we need to have a proper plan on how to achieve the best gameplay (with coding in the back of our minds too).

**Comment by Maverick283** [comment] 2016-06-13 19:06
@nielsvdweide I agree, and I think removing the whole tower function would be too much. But getting rid of that little ground stuff should be a good thing to clear up some misconceptions I believe...

**Comment by erikquinn** [comment] 2017-02-05 23:18
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.

**Closed as completed by erikquinn** 2017-02-05 23:18 UTC
Labels: undesirable behavior, closed during openscope migration
