### ISSUE TITLE
OMDB Multiple Aircraft with Same Call Sign Error

### ISSUE THREAD

**Issue by scott-j-smith** [zlsa/atc#744] opened 2016-11-23 21:59 UTC
Hi,

Playing OMDB for quite a while, and just got an error stating I have multiple aircraft with the same call sign, which is UAE540.

I checked the console and I realized one is an arrival and one is a departure.

![image](https://cloud.githubusercontent.com/assets/22403776/20580049/1e0eb130-b19e-11e6-9034-ceca74d478ef.png)

**Comment by n8rzz** [comment] 2016-11-24 00:30
I can see how that might be a thing.  I believe when callsigns are generated, they are generated without any knowledge of previously generated callsigns.

I've added an issue to my fork so we can get this fixed within the next release or two.  Thanks for the report!

**Comment by erikquinn** [comment] 2016-11-24 18:19
@n8rzz I know previously all `callsign`s were ensured to be unique upon generation (really, it was only the flight number, so for example it wouldn't create AAL527 and UAL527, because "527" is already in the formerly-named `prop.game.callsigns`).

**Comment by scott-j-smith** [comment] 2016-11-28 19:48
I'm getting the same issue on SBGL also, both are arrivals this time.  So it's not limited to the airport.

![image](https://cloud.githubusercontent.com/assets/22403776/20683331/92c1f7ec-b579-11e6-8baf-b2e168369fc3.png)

**Comment by n8rzz** [comment] 2016-11-28 19:58
@scott-j-smith I _believe_ we have this fixed in v3.2.0, but I was not able to reproduce this in my testing.

How long were you playing before you saw this issue?  Are you able to reproduce this consistently?  Or does it 'just happen sometimes'?

**Comment by scott-j-smith** [comment] 2016-11-28 20:19
@n8rzz  I was only playing for about 15 min. today before it showed up on SBGL, but almost an hour on OMDB.  It seems to be random because I played SBGL yesterday for almost an hour and it never happened, though I haven't tried to reproduce it specifically.

**Comment by n8rzz** [comment] 2016-11-28 21:20
hmm.  Ok, well that helps a little bit.  I'll run both of those on timewarp 50 and see if I can hit it.  With the changes I've made in v3.2.0, you shouldn't ever see duplicate flight numbers.  But I'll give both of these airports a try and see if I can replicate.

If you see this anywhere else, please let me know.

**Comment by scott-j-smith** [comment] 2016-11-28 21:25
Will do.  Thanks.

**Comment by erikquinn** [comment] 2016-11-28 22:58
The fact that it's again the same airline and flight number, and not just the number makes it infinitely more likely the instance is somehow being duplicated. @n8rzz I doubt the `generateFlightNumber` stuff you worked on recently isn't working. I'm sure it's fine. Is there any chance something is being `_clone`d?

**Comment by n8rzz** [comment] 2016-11-29 03:05
I just stepped through OMDB for about a half hour on timewarp 75, with the code in v3.2.0.  There were several times where a duplicate flight number was generated, however, every time it was identified as a duplicate and re-generated before leaving the `generateFlightNumber` method.

I am confident my refactor will solve this problem.

One thing we may want to look at is how the random numbers are being generated.

**Comment by XC-Zhang** [comment] 2016-12-01 03:37
Duplicate flight number occurred in EGLL after about 10 minutes, both are departure.
![bug](https://cloud.githubusercontent.com/assets/6461819/20780987/7a30b40a-b7ba-11e6-80cf-a47c31274d4b.PNG)

**Comment by henk23** [comment] 2016-12-12 09:33
Same issue here, played for just a few minutes.
![multiple](https://cloud.githubusercontent.com/assets/10068060/21094244/56e2e064-c056-11e6-987d-c2fd28c3a76f.png)

**Comment by erikquinn** [comment] 2016-12-20 02:24
Resolved by #755. Closing.

**Closed as completed by erikquinn** 2016-12-20 02:24 UTC
Labels: bug
