### ISSUE TITLE
Radar stop in KSFO

### ISSUE THREAD

**Issue by Fercajim** [zlsa/atc#531] opened 2016-05-26 17:11 UTC
Hi,

When I play at KSFO after 10-20 minutes it stops and I can't move the radar map or click on the planes.

**Comment by Fechulo** [comment] 2016-05-26 18:04
Hi @Fercajim 
I have a few questions that could make our debugging process much easier:
1) Does this only occur at KSFO?
2) Has this happened to you more than once?
3) Are there any commands you issued just before the game crashed?

**Comment by Fercajim** [comment] 2016-05-26 22:14
Hi!

1) Yes
2) Yes, and more than twice
3) Yes, it stops when I press ''Intro'' to send a message to an airplane

2016-05-26 19:04 GMT+01:00 Fechulo notifications@github.com:

**Comment by Fechulo** [comment] 2016-05-26 22:34
@Fercajim I have looked into it, and it seems like time is not the problem. This leads me to believe that the crash is caused by a specific command. When I asked you If there were any commands you issued before the crash, I was talking about a specific command, e.g., AAL123 TAXI 28L. There were recently many changes regarding how aircraft navigate. I am therefore assuming that the crash occurs when commands, such as FIX or PROCEED, are issued. Are you able to reproduce the crash? If it happens again, I would love to know what the last command was.

**Comment by erikquinn** [comment] 2016-05-27 17:21
I played for a full two hours yesterday and almost gave up before I was able to reproduce this right at the end. I recorded the whole thing in efforts to determine the cause... however, it happens seemingly without relation to a specific command, as nothing was being clicked or typed at the time that it hung.

[https://youtu.be/cpiWUtMmE6U?t=7154](https://youtu.be/cpiWUtMmE6U?t=7154)

Game freezes in the video at 1:59:21

**Comment by Fercajim** [comment] 2016-05-27 18:46
Okey, thank you very much :-)

2016-05-27 18:21 GMT+01:00 Erik Quinn notifications@github.com:

**Comment by Fechulo** [comment] 2016-05-27 19:53
@Fercajim We still need to find the issue and solve it! :smile:

**Comment by GlenBush** [comment] 2016-06-01 04:18
I am not sure if this helps but I have this problem, I love this game but really annoying it crashed like this. I have run this game both online and locally; in many browsers and on win7 win10 and linux. same thing every time. the debug gives me a lot of Unexpected token errors. i imported the folder to Unity editor and got something like 98 errors. in monodevelop i have 68 errors. I would like to see this game not freeze up the radar that is my only problem with the game. unfortunately it is a game breaker problem

**Comment by GlenBush** [comment] 2016-06-01 05:28
This. fixed is undefined
      set up  as an error log message

expected a % received undefined   from DOM

**Comment by erikquinn** [comment] 2016-06-01 05:39
@GlenBush do you mean `this.fixes`? Do you know the line it's dying on?

**Comment by GlenBush** [comment] 2016-06-01 05:46
@erikquinn 
i get this in the error log but it points to the log message code so I am not sure how to trace it back I figured that it was setup to log this message for a reason and the person who put that error logging code in would know why. I also am assuming that is why i get the other error as it is looking for for a percent but getting an undefined. I believe that it runs every cycle looking for this percent. I have been running the game trying to see the number it gets to before the radar dies.
 [ INFO ] this.fixes is undefined                      modules.js:153:7

**Comment by erikquinn** [comment] 2016-06-01 07:33
@GlenBush Have you found a way to reliably reproduce the error? I've run a 12-hour sim five times now (via `timewarp` command), and haven't been able to see the issue. I've never really been able to see it other than that one time in the video, and I can't get anywhere if I can't _observe_ it breaking. Clearly it IS breaking, but I need help creating the problem.

Based on the limited information, the issue _might_ relate to the `log()` calls on `airport.js:129`, `airport.js:241`, or `airport.js:247`. All of which come from a changeset that seems to be the right timeframe for when this issue came around. If this is where it's breaking, the `jquery.map()` command is probably the culprit.

If we could reproduce the issue, make the change, and prove its fixed, I will personally mail you a freshly baked cake. :laughing: or... something like that.

`$.map(this.fixes,function(v){return v.fix;}).join('-')`

**Comment by GlenBush** [comment] 2016-06-01 07:36
@erikquinn 
01:31:37.323 Expected a percentage but found 'undefined'.1 from DOM
 crashed at 12400 repeats

**Comment by GlenBush** [comment] 2016-06-01 07:40
@erikquinn let me see if i can record the screen for you, I would run it in unity as i am used to that but unity says there are 98 errors in the scripts, is their a good program to run this in to get a good error log with. I will actually play the game and wait til it breaks, send the video and error log

terrible video i looked up some settings will try again tonight

**Comment by GlenBush** [comment] 2016-06-01 09:35
https://youtu.be/HF9XrkPyz_0

20 mins to crash

**Comment by GlenBush** [comment] 2016-06-01 10:17
https://www.youtube.com/watch?v=HF9XrkPyz_0

**Comment by GlenBush** [comment] 2016-06-01 13:18
@erikquinn I have now two videos on youtube of the crashes in this playlist. This is a first time for me recording and uploading to youtube so I so I hoe this will hel
https://www.youtube.com/watch?v=8QA6s1clONY&index=1&list=PLDRDNh-UNwP1nnhVd3EhSvVN821xU0wKT

**Comment by erikquinn** [comment] 2016-06-01 21:06
Some good news, mostly bad news here...

### Good news:

I found what @GlenBush is talking about. Chrome was just showing `"[ INFO ] Cannot read property 'hasOwnProperty' of undefined"` via `modules.js:153`, which is simply the logic that creates the log message, and provided zero guidance to the actual reason behind the `hasOwnProperty` method not being able to run. _However_, Firefox provides more useful information, saying `"this.fixes"` is undefined at the same lines, which led me to find the one time that the `hasOwnProperty` method is called on `this.fixes`, which is on `airport.js:1138`, in relation to the fix validation logic. It was simply an issue of `this` not being in the intended context. _This issue with the log_ (not the problem in discussion on this page) is fixed as of PR #543.

Firebug console _BEFORE_:
![image](https://cloud.githubusercontent.com/assets/5103735/15725427/7272596e-2811-11e6-8bd2-8ce78225093f.png)

Firebug console _AFTER PR #543_:
![image](https://cloud.githubusercontent.com/assets/5103735/15725459/ac1c8144-2811-11e6-983e-17f46e38cd58.png)
![image](https://cloud.githubusercontent.com/assets/5103735/15725516/029273f8-2812-11e6-9dd0-665ce7c49ef6.png)

### Bad News:

None of this has anything to do with the issue at hand. With that problem resolved, the console is now back to empty, and not displaying any clues to what might be going wrong. So... it's mostly bad news, actually. But, there _has_ to be a way to figure it out, and if we keep at it, it _will_ be found and fixed.

**Comment by erikquinn** [comment] 2016-06-01 23:23
From the second video, this was helpful:
![image](https://cloud.githubusercontent.com/assets/5103735/15728746/224d2c30-2824-11e6-9b17-997713293a2a.png)

Apparently, at some point, there is a waypoint being created that uses "fix" navmode, but doesn't have a location to navigate to, which could be caused by a fix that isn't defined, which would be throwing an error in the console, as seen in my previous comment. Not sure why else there would be a navmode waypoint without a `.location`.

For now, I will push in a change that will log the entire fms to the console whenever the freeze shown in the second video happens. That should provide a lot of insight as to _WHY_ it's doing it, and from there we will know where to start checking the code.

**Comment by GlenBush** [comment] 2016-06-02 02:01
I will play again now to see if i can produce another crash.

**Comment by GlenBush** [comment] 2016-06-02 03:15
@erikquinn 
I will take my cake in the form of a menu that you can click on the plane and choose the commands to give it. once you have figured out the commands you hit ok and it puts the commands in the console

https://github.com/zlsa/atc/issues/463

**Comment by GlenBush** [comment] 2016-06-02 21:01
I can no longer get the radar to crash,

**Comment by erikquinn** [comment] 2016-06-03 05:01
@GlenBush that might be good news. I don't have any reason to think it would be fixed, but if it nobody encounters the freeze in the next week or so, perhaps then we can say it's resolved.

**Comment by anishthecoder** [comment] 2016-06-06 04:39
Just got a similar crash of the simulation again. This time, none of the planes were close to landing. I'd just managed to set some of them on standard departures and just had three on arrival. Nothing had come close to ILS

![image](https://cloud.githubusercontent.com/assets/5558945/15812100/6dd7c2fa-2b76-11e6-92e4-9c3a84af11bd.png)

**Comment by erikquinn** [comment] 2016-06-06 11:05
@anishthecoder Are you rerouting aircraft?

@ALL by the way, the next time anyone sees this, the logging has been improved; please expand the following sections pictured below to provide the additional information. Your example should have the circled "location" undefined, and knowing what the fix is that doesn't have a location would be helpful to know.

![image](https://cloud.githubusercontent.com/assets/5103735/15820016/2b679acc-2bac-11e6-9547-d49e2d679cbc.png)

**Comment by GlenBush** [comment] 2016-06-07 22:23
I played again today for over 2 hours and could not recreate any crash

**Closed as completed** 2016-06-10 12:45 UTC
Labels: bug - high priority

**Comment by erikquinn** [comment] 2016-06-13 16:27
Oh, thank god this is fixed... thanks @tedrek!!!
