### ISSUE TITLE
Refusal to takeoff

### ISSUE THREAD

**Issue by dutchdavey** [zlsa/atc#778] opened 2017-01-06 10:34 UTC
Im getting sometimes, aircraft which wont budge from Waiting to takeoff, even if cvs or an altitude command has been given.

**Comment by n8rzz** [comment] 2017-01-06 12:46
@dutchdavey could you provide a few more details?  
- What browser were you using
- What airport
- Did you taxi the aircraft to a specific runway or just use `taxi`  
- Was the runway valid
- Did you see any errors in the DevTools console
- Did the sim freeze afterwards
- Did this happen early in the sim or only after playing for a while
- Can you reproduce this (and if so, what are the steps to reproduce)

**Comment by dutchdavey** [comment] 2017-01-06 16:36
Chrome
SFO
taxi
I don't know, in any case the aircraft remain unuseable.
I dont know where that is, let me know and Ill check..
No, sim continues to work, but the aircraft are unuseable
Playing for a while
I'm still trying to reproduce it reliably

**Comment by dutchdavey** [comment] 2017-01-06 16:37
Ive got 4 stuck at waiting right now.

**Comment by dutchdavey** [comment] 2017-01-06 16:40
![untitled](https://cloud.githubusercontent.com/assets/6518178/21725088/3390e314-d437-11e6-8adb-1c3a51c5bfe8.png)

**Comment by dutchdavey** [comment] 2017-01-06 16:48
Coulld it be related to a performance issue on a slow PC? Timeouts maybe?

this laptop slows appallingly once the sim has been running for some time.

**Comment by n8rzz** [comment] 2017-01-06 17:02
Hmm.  Do you still have the same problem if you taxi one aircraft, then clear it to takeoff?  Do you get the same problem with _all_ the aircraft waiting to takeoff?  My guess is you are trying to clear an aircraft that is not first in line.  

That console error suggests it could be a different issue, though.

**Comment by n8rzz** [comment] 2017-01-06 17:13
just running through it quick I am unable to reproduce your issue, even after taxiing several aircraft and clearing them out of order.

The decreased performance is likely due to drawing the projected routes for all aircraft.  That takes a lot of work to do, and the more aircraft the more power it needs.  That will be improved in the future.

**Comment by dutchdavey** [comment] 2017-01-06 20:31
I don't think its to do with a takeoff queue. As I said, once it happens, the affected aircraft won't take off, none of them, even if you wait a half hour.. I still have the same four waiting at the moment..

**Comment by n8rzz** [comment] 2017-01-06 21:29
If you have the sim still paused, try and delete all the departures (or at least the ones that are stuck).  You can do that by issuing a delete command: `CALLSIGN del`.

That will completely remove an aircraft from the sim and should clear the present log jam.

I'm more concerned with how you got to that spot.  I haven't been able to reproduce this issue at all in any of our environments.  Any additional information you can provide, or steps leading up to the issue, would help immensely in trying to spot where this is coming from.

**Comment by dutchdavey** [comment] 2017-01-08 14:54
I decided at some point to use the command 'caf taxi' to get the aircraft to the takeoff runway, and then to use 'a 2 to' or 'a 3 to' or 'cvs to' to get them in the air, depending on the traffic. It seems, though I'm not sure, that this is where the anomaly started to appear.

Incidentally there isn't any log jam in any case. Aircraft still use both 28l and 28r! (The stopped planes remain stopped, rather like in Douglas Adams book)

**Comment by dutchdavey** [comment] 2017-01-09 15:05
That doesnt seem to be relevant either, alas. I still get it with 'caf cvs taxi' followed by 'to'.

**Comment by n8rzz** [comment] 2017-01-09 19:50
@dutchdavey I am still unable to reproduce this.  Could you give it a try here: http://atc-dev.herokuapp.com

That is running my current `develop` branch and, in a few weeks, will be the next version released.

If you _still_ get this error there, please provide a list of commands you used to cause the error.  I am unable to reproduce this error by running the commands above.

**Comment by dutchdavey** [comment] 2017-01-11 14:55
will do..

**Comment by scott-j-smith** [comment] 2017-01-12 03:57
I had this problem too, and I'm also using Chrome.  It can happen even if only issuing the 'w' or 'taxi' command to a single aircraft and not creating a queue.  Because of the other bug where a landing arrival will cause a waiting departure to disappear, I have been making sure to only tell a flight to taxi when no arrivals are close to landing, and this issue where a flight will appear to taxi but won't take off happens.  Usually when I see it, the plane won't appear on the screen even.  And I was playing at a different airport than dutchdavey by the way.  I will also try this on the dev branch linked above later tonight.

I can clear the issue by deleting the frozen departure and continuing to the next one.

**Comment by scott-j-smith** [comment] 2017-01-12 04:58
@n8rzz 
I played for over 30 min. on timewarp 5 on LKPR on your development branch and could not replicate this issue there either, and I really tried to make it happen.   Maybe one of the fixes for the other bugs also addressed this?   I must say it was nice to play without worrying that waiting departures would disappear if another plane landed, or that every plane would change to heading 360 at the end of their assigned routes all the time.  :-)   Can't wait for 3.2.1 to merge to fix these issues.

**Comment by n8rzz** [comment] 2017-01-12 05:08
@scott-j-smith  Thanks for taking a look!  I'm glad to hear you were not able to replicate.  This feels like a sneaky issue and I'm not totally convinced that it is fixed in `develop`.  

Perhaps there is a race condition somewhere?  Perhaps this is a side effect of a completely different issue?  I don't know.  I'd love to say the glitch is gone, but I know better 😉 

@dutchdavey did you have any luck reproducing in our develop env?

**Comment by dutchdavey** [comment] 2017-01-12 10:11
No, I couldn't reproduce it either on development.

Looks to me like a classic automagical fix!

**Comment by n8rzz** [comment] 2017-01-12 12:38
![fixed-the-glitch](https://cloud.githubusercontent.com/assets/3325985/21890105/bba20cde-d891-11e6-81d7-0091abd21fdd.jpg)

**Comment by LeGiraffe** [comment] 2017-01-13 11:38
I have actually come across the same issue.

Running in any of the airports...
Mac using Safari
Multiple aircraft appear "waiting" and refuse to do anything.

It occurs when, you have used "Taxi" to a runway and they are "waiting" for "takeoff".
If a arriving aircraft lands, at the moment it is cleared and "contacting ground" appears, all aircraft on the airport waiting are partially removed (radar tag), whilst the strip remains.

Perhaps something is clearing all traffic on the airport instead of just the aircraft that has landed.

**Comment by scott-j-smith** [comment] 2017-01-13 16:35
@matt5611  
I think that is a different bug that I reported earlier too.  The bug discussed in this issue is not related to the case where an aircraft lands and the waiting plane is removed from radar and then can't take off.

**Comment by scott-j-smith** [comment] 2017-01-13 16:38
@n8rzz 
Nate - your development branch code might have an issue with the collision warning (white) and alert (red) circles not working.  I was playing OTHH and two aircraft coming in on different arrival STAR's ended up almost colliding at the same altitude and speed -- no warnings were shown.  See screen shot below.

Flights QTR4205 on the AFNAN arrival, and QTR3894 on the BAYAN arrival.

![image](https://cloud.githubusercontent.com/assets/22403776/21937285/c0918ef6-d984-11e6-98d9-7ae27e98ef34.png)

**Comment by n8rzz** [comment] 2017-01-13 16:50
hmm, thanks @scott-j-smith!  Could you open an issue in my fork for that (with that screenshot)?  That looks like it could be a side effect from one of the features completed this sprint.

re: @erikquinn

**Comment by scott-j-smith** [comment] 2017-01-13 18:20
@n8rzz 
Done!

**Comment by erikquinn** [comment] 2017-01-16 20:41
>@matt5611:
>It occurs when, you have used "Taxi" to a runway and they are "waiting" for "takeoff".
>If a arriving aircraft lands, at the moment it is cleared and "contacting ground" appears, all aircraft on the airport waiting are partially removed (radar tag), whilst the strip remains.

>@scott-j-smith:
>@matt5611 I think that is a different bug that I reported earlier too. The bug discussed in this issue is not related to the case where an aircraft lands and the waiting plane is removed from radar and then can't take off.

I concur with @matt5611. This is almost definitely a similar symptom to that described in #770; both symptoms are resolved following n8rzz/atc#241. This also explains why it is broken at `zlsa/gh-pages`, but working at `n8rzz/develop`. When #776 (v3.2.1) is merged, this will be resolved.

**Closed as completed** 2017-01-20 04:57 UTC
