### ISSUE TITLE
Mysterious plane at Gatwick

### ISSUE THREAD

**Issue by Alpi-no** [zlsa/atc#501] opened 2016-05-16 20:30 UTC
<img width="2560" alt="pic" src="https://cloud.githubusercontent.com/assets/19208045/15302934/bd539d48-1bb5-11e6-90f1-d885eded7f2d.png">

right at the beginning. I couldn't spot a plane! The time differences between the entry and the problem is not a lot. Like 1 or 2 seconds. I don't even know, whether the plane gets a strip

**Comment by erikquinn** [comment] 2016-05-16 20:49
![image](https://cloud.githubusercontent.com/assets/5103735/15303490/b27eb322-1b7d-11e6-87e2-bb2771bd4ca6.png)

**Comment by Fechulo** [comment] 2016-05-16 20:57
@jakobeng1303 that's my bad, I didn't test it with the new arrival flows, and I believe all arrivals have some kind of offset, which might be the reason why no aircraft spawn at the beginning.

@erikquinn I'm not sure what's happening in the picture, is this a bug related to the new flows or is it caused by the airport file itself?

**Comment by erikquinn** [comment] 2016-05-16 21:07
I just threw it up there as a note for later in case I couldn't figure it out now, but I cracked it. Wasn't too bad. And it may have something to do with the distance out the aircraft are spawning from. They're a long way away, and that's something the game didn't like previously. I just apparently hadn't found _all_ of the places where I needed to tell it to shut up and deal with it. lol fixed in #502.

**Closed as completed** 2016-05-16 21:07 UTC
Labels: bug
