### ISSUE TITLE
Seems to crash when playing with speed multiplier for extended periods

### ISSUE THREAD

**Issue by anishthecoder** [zlsa/atc#483] opened 2016-05-10 04:18 UTC
I've tried playing this in multiple browsers, and any time I use the speed multipliers for too long, the game eventually hangs. I don't see any console errors, but the entire interface becomes unresponsive...

However, really really great game!

**Comment by Fechulo** [comment] 2016-05-10 16:18
Does this happen in all airports or in a specific one? If so, which airport?

**Comment by anishthecoder** [comment] 2016-05-10 16:33
I've tried this on a few different of airports and it seemed to happen in each of the cases: San Francisco (primarily), LAX, and Heathrow. If I ever used the speed multiplier (even just a couple of times), it would hang before I could clear around 20 flights. I'm trying it out without the speed multiplier and will let you know if it still crashes.

**Comment by Fechulo** [comment] 2016-05-10 16:37
thanks, I'll look into it!

**Comment by erikquinn** [comment] 2016-05-10 19:13
@anishthecoder By chance, does this happen as an aircraft is in the process of trying to join the localizer? (I have a feeling it may be `aircraft.js:2217`, as `this.rwy_dep` will be null for arrivals)

**Comment by anishthecoder** [comment] 2016-05-11 01:42
@erikquinn Was trying to verify that, but having trouble because of a new issue #488

**Comment by anishthecoder** [comment] 2016-05-11 05:38
@erikquinn Yes, this does appear to happen in the process of trying to join the localizer (but it could just be my perception, there's a lot happening in traffic when it does crash)

**Comment by erikquinn** [comment] 2016-05-11 05:58
@anishthecoder Okay, so maybe that is what's causing it. And now that I think about it, that could make sense. Perhaps using the speed multiplier is causing it to be too far away to start the turn at one time, and at the next update, be too far past the point where they should have turned, thus exacerbating the problem. _This could be it_.

I made the puny little change I described above. At your leisure, please try out this link and advise if the problem is fixed there (while I sit here and cross my fingers, hoping it is this easy :wink:)

[http://erikquinn.github.io/atc/b/483-test](http://erikquinn.github.io/atc/b/483-test)

**Comment by anishthecoder** [comment] 2016-05-11 07:22
@erikquinn Sadly not.... :smile: Just tried and it hung again. This time though, it seemed to happen just when one of the landing crafts was ready to switch to ground (or it looked like that spot on the runway where it's ready to switch to ground). There were no new localizer capture attempts.

**Comment by anishthecoder** [comment] 2016-05-11 07:23
@erikquinn Surprisingly, when I left the window hung for a while and zoomed in and out using my scroll wheel, things started working again.... :open_mouth: and then hung again when I tried the speed multiplier again... this time with no recovery

**Comment by Alpi-no** [comment] 2016-05-15 10:42
I had the same problem in the demo (#493), the game suddenly stopped: nothing moved and changed, all the planes disappeared, but the trails were still visible and wouldn't decay. It happened when I tried to line up the second plane onto ILS 28R (KSFO), and right before the final turn it crashed.

**Comment by erikquinn** [comment] 2016-06-03 20:20
Duplicate of #531. Closing. Work will be tracked in the other bug.

**Closed as completed by erikquinn** 2016-06-03 20:20 UTC
Labels: duplicate
