### ISSUE TITLE
Scrollbar netzt to strips in FF

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#471] opened 2016-05-04 15:33 UTC
Hi, i just saw, there´s a browser-scrollbar next to the strips in Firefox 46. Don´t know since when.

![image](https://cloud.githubusercontent.com/assets/11310456/15019419/4450aefe-121e-11e6-9a8b-798230304393.png)

**Comment by erikquinn** [comment] 2016-05-04 19:08
I don't think I can fix this (I suck at CSS), but I can add a few notes from what I can see...

Looks like firefox is not adding the styling to the fancy scrollbar as described in `sidebar.css`. Below is the css that is getting applied to `#strips` in Chrome, but NOT in Firefox:

![image](https://cloud.githubusercontent.com/assets/5103735/15025797/a50273e0-1200-11e6-87f0-3363ece1ae32.png)

Firefox does, however, show the `#strips` element having the `nice-scrollbar` class, which should cause those styles to be applied... I would think?

**Comment by BilSot** [comment] 2016-07-27 20:39
> Don´t know since when.

Since forever. Actually `webkit-scrollbar-*` pseudoclasses are only supported by webkit as the name implies. As it's mentioned in [this](http://stackoverflow.com/a/6165489/5468384) stackoverflow answer the issue is still open and the solution could be based on jQuery. The same behavior appears in Internet Explorer 11 as well.

I think that the pain is too much for just a scrollbar (the game has bigger priorities) so I propose the closure of the issue. But if there is any interest in this, I could try a solution involving js.

**Comment by erikquinn** [comment] 2017-02-05 23:20
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.

**Closed as completed by erikquinn** 2017-02-05 23:20 UTC
Labels: bug, help wanted, closed during openscope migration
